name: 'tab count in modified files'
on:
  push:
  pull_request:
jobs:
  checkfile:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
      for changed_file in ${{ steps.files.outputs.all }}; do
      echo "File ${changed_file} has $(grep -o $"\t" ${changed_file} | wc -l) tab" >> test_tab.log 2>&1
      done  
    #- id: files
     # uses: jitterbit/get-changed-files@v1
      #with:
       # format: 'csv'
    #- run: |
     #   mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
      #  for added_modified_file in "${added_modified_files[@]}"; do
      #  echo "File ${added_modified_file} has $(grep -o $"\t" ${added_modified_file} | wc -l)" >> test_tab.log 2>&1
      #  done
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: test_tab.log