name: Scan all chaged files

on: push

jobs:
  checkfiles:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
          echo $(grep -o $'\t' ${added_modified_file} | wc -l) tabs - ${added_modified_file} >> 04gitops.log 2>&1 
          done
        name: Upload gitops  
      - uses: actions/upload-artifact@v3
        with:
          path: 04gitops.log